### ISSUE TITLE
Staircase/steps scribble type

### ISSUE THREAD

**Issue by Colbertson** [Zverik/geoscribble#3]
Add a step scribble type, footway/path is usually easy enough to see from aerial but steps are more specific 
Maybe style it with arrows to indicate which way leads up
(Not sure if I should have posted this as an everydoor issue)

**Comment by Zverik** [comment]
Yeah this should go to Every Door — this backend doesn't know anything about specific categories.

But then, steps don't occur very often so idk. Would be possible with https://github.com/Zverik/every_door/issues/119 if/when I get a grant for that :)
